DROP DATABASE IF EXISTS ;
CREATE DATABASE ;
USE ;

CREATE TABLE department (
id INT NOT NULL,
name VARCHAR(30) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE role(
id INT NOT NULL,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL,
FOREIGN KEY (department_id) INT,
REFERENCES department(id)
);

CREATE TABLE employee(
id INT NOT NULL,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
FOREIGN KEY (role_id) INT NOT NULL,
REFERENCES role(id),
REFERENCES manager(id) INT NOT NULL
);
